version: "3"


dotenv: ['.env']

tasks:
  sso-run:
    desc: "run sso server"
    cmds:
      - go run ./cmd/sso/main.go
  sso-pprun:
    desc: "run sso server with pplog"
    cmds:
      - pplog go run ./cmd/sso/main.go
  goose-up:
    desc: "run goose migrations"
    cmds:
      - goose -dir ./migrations postgres "host=$PG_HOST user=$PG_USER password=$PG_PASS dbname=$PG_DBNAME port=$PG_PORT sslmode=$PG_SSLMODE" up
